"""The only place a filter becomes SQL.

Takes a `dsl.FilterNode` and returns a SQLAlchemy boolean expression to hang off
a `WHERE`. Field rules become comparisons on `leads.values`; the four history
predicates become correlated `EXISTS` / `NOT EXISTS` subqueries over `actions`.

Four rules this module exists to enforce:

1. **Values are always bound parameters.** The DSL carries customer-supplied
   data and it is never interpolated. What *is* interpolated is the JSONB key —
   see `_json_path` for why that is both necessary and safe.
2. **Operators come from the registry.** `spec.operators` decides what a field
   type supports. There is no second table of "which operators does DATE
   offer?" here; if there were, the two would disagree within a milestone.
3. **Every key is permission-checked before it is compiled.** Filtering on a
   field the caller cannot View is a *read* of that field: `stage = X AND
   salary > 100000` returning a count of 1 is an oracle. `filterable()` gates it.
4. **Relative windows resolve in the workspace's timezone**, never the
   server's (architecture rule 10).
"""

from __future__ import annotations

import datetime as dt
import re
import uuid
from collections.abc import Mapping, Sequence
from decimal import Decimal, InvalidOperation
from typing import TYPE_CHECKING, Any
from zoneinfo import ZoneInfo

from sqlalchemy import Boolean, Date, Numeric, and_, exists, func, literal_column, not_, or_, select
from sqlalchemy.sql.elements import ColumnElement

from app.errors import unprocessable
from app.fields.registry import LEAD_FIELD_TYPES
from app.fields.search import SEARCH_CONFIG
from app.filters.dsl import (
    ActionNotPerformedNode,
    ActionPerformedNode,
    AssigneeChangedNode,
    FieldRuleNode,
    FilterNode,
    GroupNode,
    StatusChangedNode,
    Within,
)
from app.models.enums import LeadFieldType, SystemActionKind
from app.models.field import LeadField
from app.models.lead import Action, Lead

if TYPE_CHECKING:  # pragma: no cover
    # Only ever a type here. `app.permissions` and `app.tenancy` already
    # import each other at runtime, and joining that cycle would make
    # importing the compiler first fail depending on entry point.
    from app.permissions.projection import FieldProjectionService

__all__ = ["FilterCompiler"]

#: A field key is generated by `slugify_key`, so it is always this shape. The
#: pattern is re-checked here rather than assumed: this is the one value that
#: reaches SQL as text rather than as a parameter, and "it came from our own
#: table" is an assumption, not a guarantee.
_SAFE_KEY = re.compile(r"^[a-z0-9_]{1,64}$")

#: Sub-keys that hold the comparable value inside a composite type.
_COMPOSITE_VALUE_KEY: Mapping[LeadFieldType, str] = {
    LeadFieldType.MONEY: "amount",
    LeadFieldType.DEPENDENT_DROPDOWN: "value",
    # The derived next occurrence, not the original start: "whose renewal falls
    # in the next 30 days" is a question about the next one.
    LeadFieldType.RECURRING_DATE: "next",
}

#: LOCATION is structured, but its operators are textual. Comparisons run
#: against the address lines joined together, so `contains "Chennai"` matches
#: whichever part holds it.
_LOCATION_PARTS = ("line1", "line2", "city", "state", "postal_code", "country")


def _json_path(key: str, *sub: str) -> str:
    """The SQL text for reaching a value inside `leads.values`.

    This is the one identifier-shaped thing that is written into SQL rather than
    bound, and it has to be. The indexed-field worker builds its expression
    indexes as `(workspace_id, (values ->> 'key'))`, and Postgres matches an
    expression index by comparing expression *trees* — a bind parameter is a
    Param node, not the Const the index was built with, so `values ->> $1` can
    never use it. Emitting the literal is what makes an indexed field actually
    fast, which is the entire point of declaring one.

    Safety is the same argument the worker makes: the key is generated by
    `slugify_key`, and it is re-validated here before it is used.
    """
    if not _SAFE_KEY.match(key):
        raise unprocessable("invalid_field_key", f"{key!r} is not a valid field key")
    for part in sub:
        if not _SAFE_KEY.match(part):  # pragma: no cover - our own constants
            raise unprocessable("invalid_field_key", f"{part!r} is not a valid sub-key")

    if not sub:
        return f"leads.values ->> '{key}'"
    # `->` down to the last step, `->>` for the final one, so the result is text.
    path = f"leads.values -> '{key}'"
    for part in sub[:-1]:
        path += f" -> '{part}'"
    return f"{path} ->> '{sub[-1]}'"


def _escape_like(value: str) -> str:
    r"""Escape LIKE wildcards in a user's search text.

    Without this, searching for `50%` matches everything ending in 50, and `_`
    matches any character. Backslash first, or it would escape the escapes.
    """
    return value.replace("\\", "\\\\").replace("%", r"\%").replace("_", r"\_")


class FilterCompiler:
    """Compiles one workspace's filter DSL against one caller's grants.

    Constructed per request: it closes over the field definitions, the caller's
    projection and the workspace timezone, so no method can accidentally compile
    against another workspace's schema or another caller's permissions.
    """

    def __init__(
        self,
        *,
        fields: Sequence[LeadField],
        projection: FieldProjectionService,
        timezone: str,
        now: dt.datetime | None = None,
    ) -> None:
        self._fields = {f.key: f for f in fields}
        self._projection = projection
        self._timezone = timezone
        self._now = now or dt.datetime.now(dt.UTC)

    # --- entry point -------------------------------------------------------

    def compile(self, node: FilterNode) -> ColumnElement[bool]:
        """The boolean expression for a whole filter tree."""
        if isinstance(node, GroupNode):
            return self._group(node)
        if isinstance(node, FieldRuleNode):
            return self._field_rule(node)
        if isinstance(node, ActionPerformedNode):
            return self._action_performed(node)
        if isinstance(node, ActionNotPerformedNode):
            return self._action_not_performed(node)
        if isinstance(node, StatusChangedNode):
            return self._status_changed(node)
        if isinstance(node, AssigneeChangedNode):
            return self._assignee_changed(node)
        raise unprocessable(  # pragma: no cover - the union is closed
            "unknown_filter_node", f"{node!r} is not a filter node"
        )

    # --- groups ------------------------------------------------------------

    def _group(self, node: GroupNode) -> ColumnElement[bool]:
        if not node.children:
            # The identity: an empty filter matches everything, so clearing the
            # builder behaves the same as never opening it.
            return literal_column("true", type_=Boolean)
        parts = [self.compile(child) for child in node.children]
        return and_(*parts) if node.op == "AND" else or_(*parts)

    # --- field rules -------------------------------------------------------

    def _field_rule(self, node: FieldRuleNode) -> ColumnElement[bool]:
        field = self._fields.get(node.key)
        if field is None:
            raise unprocessable("unknown_field", f"No field named {node.key!r} in this workspace")
        # Rule 3 — before anything else. A filter on a field the caller cannot
        # view must not be compilable, whatever the operator.
        if not self._projection.filterable(node.key):
            # Deliberately the same error as an absent field: telling the caller
            # "you may not filter that" confirms the field exists, which is the
            # leak this check exists to prevent.
            raise unprocessable("unknown_field", f"No field named {node.key!r} in this workspace")

        spec = LEAD_FIELD_TYPES[field.field_type]
        if node.op not in spec.operators:
            raise unprocessable(
                "unsupported_operator",
                f"{field.label} is a {spec.label} field, which does not support {node.op.value!r}",
                field_key=node.key,
                supported=[op.value for op in spec.operators],
            )

        from app.fields.operators import Operator as Op

        # Presence is asked the same way of every type, but answered differently
        # per storage shape, so it is handled before the type dispatch.
        if node.op is Op.IS_EMPTY:
            return self._is_empty(field)
        if node.op is Op.IS_NOT_EMPTY:
            return not_(self._is_empty(field))

        if field.field_type is LeadFieldType.TAGS:
            return self._tags_rule(field, node)
        return self._scalar_rule(field, node)

    def _is_empty(self, field: LeadField) -> ColumnElement[bool]:
        """Absent, JSON null, empty string, or empty list — all "no value".

        `_blank_to_none` in the registry collapses these on write, so this is
        mostly belt and braces; it matters for values written before a field's
        type changed, and for anything an import wrote.
        """
        if field.field_type is LeadFieldType.TAGS:
            array: ColumnElement[Any] = literal_column(
                f"coalesce(leads.values -> '{field.key}', '[]'::jsonb)"
            )
            if not _SAFE_KEY.match(field.key):  # pragma: no cover - checked above
                raise unprocessable("invalid_field_key", field.key)
            return func.jsonb_array_length(array) == 0
        target: ColumnElement[Any] = literal_column(_json_path(field.key, *self._sub_keys(field)))
        return or_(target.is_(None), target == "")

    def _sub_keys(self, field: LeadField) -> tuple[str, ...]:
        if (sub := _COMPOSITE_VALUE_KEY.get(field.field_type)) is not None:
            return (sub,)
        return ()

    def _accessor(self, field: LeadField) -> ColumnElement[Any]:
        """The comparable SQL expression for this field's stored value."""
        field_type = field.field_type

        if field_type is LeadFieldType.LOCATION:
            # Joined with spaces so `contains` can match any part without the
            # caller knowing which sub-key holds it.
            parts = [f"coalesce({_json_path(field.key, p)}, '')" for p in _LOCATION_PARTS]
            return literal_column(f"concat_ws(' ', {', '.join(parts)})")

        path = _json_path(field.key, *self._sub_keys(field))

        if field_type in {LeadFieldType.NUMBER, LeadFieldType.MONEY}:
            # `numeric` and not float: MONEY is stored as an exact string and
            # comparing it through a float would reintroduce the rounding the
            # registry went to trouble to avoid.
            return literal_column(f"({path})::numeric", type_=Numeric)
        if field_type in {LeadFieldType.DATE, LeadFieldType.RECURRING_DATE}:
            return literal_column(f"({path})::date", type_=Date)
        if field_type is LeadFieldType.CHECKBOX:
            return literal_column(f"({path})::boolean", type_=Boolean)
        return literal_column(path)

    def _coerce(self, field: LeadField, raw: Any) -> Any:
        """Turn a JSON operand into the Python type the column compares against.

        Deliberately *not* the registry's `normalise`: that validates a value
        for storage, and a filter operand is a different thing — `contains
        "gmail"` is not a valid EMAIL but is a perfectly good filter.
        """
        field_type = field.field_type
        try:
            if field_type in {LeadFieldType.NUMBER, LeadFieldType.MONEY}:
                return Decimal(str(raw))
            if field_type in {LeadFieldType.DATE, LeadFieldType.RECURRING_DATE}:
                return raw if isinstance(raw, dt.date) else dt.date.fromisoformat(str(raw))
            if field_type is LeadFieldType.CHECKBOX:
                if isinstance(raw, bool):
                    return raw
                return str(raw).strip().lower() in {"true", "1", "yes"}
        except (InvalidOperation, ValueError, TypeError) as exc:
            raise unprocessable(
                "invalid_filter_value",
                f"{raw!r} is not a valid value to compare {field.label} against",
                field_key=field.key,
            ) from exc
        return str(raw)

    def _scalar_rule(self, field: LeadField, node: FieldRuleNode) -> ColumnElement[bool]:
        from app.fields.operators import Operator as Op

        target = self._accessor(field)
        op = node.op

        if op in {Op.IN, Op.NOT_IN}:
            values = [self._coerce(field, v) for v in node.value]
            return target.in_(values) if op is Op.IN else not_(target.in_(values))

        if op is Op.BETWEEN:
            low, high = (self._coerce(field, v) for v in node.value)
            return target.between(low, high)

        if op in {Op.IN_LAST_DAYS, Op.IN_NEXT_DAYS}:
            days = int(node.value)
            today = self._today()
            if op is Op.IN_LAST_DAYS:
                return target.between(today - dt.timedelta(days=days), today)
            return target.between(today, today + dt.timedelta(days=days))

        if op in {Op.CONTAINS, Op.NOT_CONTAINS, Op.STARTS_WITH, Op.ENDS_WITH}:
            text = _escape_like(str(node.value))
            pattern = {
                Op.CONTAINS: f"%{text}%",
                Op.NOT_CONTAINS: f"%{text}%",
                Op.STARTS_WITH: f"{text}%",
                Op.ENDS_WITH: f"%{text}",
            }[op]
            # ilike: a CRM search for "gmail" must find "GMail".
            match = target.ilike(pattern, escape="\\")
            if op is Op.NOT_CONTAINS:
                # A lead with no value at all does not "contain" the text, so it
                # belongs in a not-contains result. Without the coalesce the NULL
                # would make the whole predicate NULL and drop the row.
                return or_(target.is_(None), not_(match))
            return match

        value = self._coerce(field, node.value)
        comparisons: Mapping[Op, ColumnElement[bool]] = {
            Op.EQUALS: target == value,
            Op.NOT_EQUALS: or_(target.is_(None), target != value),
            Op.GREATER_THAN: target > value,
            Op.GREATER_OR_EQUAL: target >= value,
            Op.LESS_THAN: target < value,
            Op.LESS_OR_EQUAL: target <= value,
        }
        return comparisons[op]

    def _tags_rule(self, field: LeadField, node: FieldRuleNode) -> ColumnElement[bool]:
        """TAGS is a JSON array, so its operators are set operations.

        Uses the function spellings (`jsonb_exists_any`) rather than the `?|`
        and `?&` operators: a literal `?` in the SQL collides with the
        placeholder syntax of several DBAPIs, and the functions are exactly
        equivalent.
        """
        from app.fields.operators import Operator as Op

        array: ColumnElement[Any] = literal_column(
            f"coalesce(leads.values -> '{field.key}', '[]'::jsonb)"
        )
        if not _SAFE_KEY.match(field.key):  # pragma: no cover - checked in _field_rule
            raise unprocessable("invalid_field_key", field.key)
        codes = [str(v) for v in node.value]

        if node.op is Op.HAS_ANY:
            return func.jsonb_exists_any(array, codes)
        if node.op is Op.HAS_ALL:
            return func.jsonb_exists_all(array, codes)
        if node.op is Op.NOT_IN:
            return not_(func.jsonb_exists_any(array, codes))
        raise unprocessable(  # pragma: no cover - registry limits TAGS to the above
            "unsupported_operator", f"{node.op.value} is not supported on a tag field"
        )

    # --- history predicates ------------------------------------------------

    def _today(self) -> dt.date:
        """Today, in the workspace's timezone.

        Architecture rule 10. A workspace in Asia/Kolkata rolls over five and a
        half hours before a UTC server does, and "called today" has to mean the
        customer's today or the morning report is wrong.
        """
        return self._now.astimezone(ZoneInfo(self._timezone)).date()

    def _window(self, within: Within | None) -> list[ColumnElement[bool]]:
        """Time bounds on `actions.performed_at`, as a list to splat into and_.

        Absolute bounds are widened to whole days *in the workspace's timezone*
        and then compared as instants, so "from the 1st to the 31st" includes
        everything that happened on the 31st locally.
        """
        if within is None:
            return []

        zone = ZoneInfo(self._timezone)
        if within.last_days is not None:
            start = self._now - dt.timedelta(days=within.last_days)
            return [Action.performed_at >= start]

        bounds: list[ColumnElement[bool]] = []
        if within.from_ is not None:
            start_local = dt.datetime.combine(within.from_, dt.time.min, tzinfo=zone)
            bounds.append(Action.performed_at >= start_local)
        if within.to is not None:
            # Exclusive upper bound on the next day: `<= 23:59:59` would drop
            # anything in the last second, and microseconds are stored.
            end_local = dt.datetime.combine(
                within.to + dt.timedelta(days=1), dt.time.min, tzinfo=zone
            )
            bounds.append(Action.performed_at < end_local)
        return bounds

    def _payload_match(self, payload: Mapping[str, Any]) -> list[ColumnElement[bool]]:
        """`payload->>'k' = 'v'` per key.

        The key is a caller-supplied string here, unlike a field key, so it is
        *not* interpolated — `Action.payload[k].astext` binds it. These
        predicates are not index-backed anyway; they narrow a set the kind
        filter has already reduced.
        """
        return [Action.payload[key].astext == str(value) for key, value in payload.items()]

    def _action_conditions(
        self,
        *,
        action_kind: SystemActionKind | None,
        action_type_id: uuid.UUID | None,
        actor_id: uuid.UUID | None,
        payload_match: Mapping[str, Any],
        within: Within | None,
    ) -> list[ColumnElement[bool]]:
        """The correlated conditions shared by all four history predicates."""
        conditions: list[ColumnElement[bool]] = [
            Action.lead_id == Lead.id,
            # Correlated on the tenant too. The scoped session would add this to
            # a top-level SELECT, but this subquery is built by hand and rule 1
            # does not bend for subqueries.
            Action.workspace_id == Lead.workspace_id,
        ]
        if action_kind is not None:
            conditions.append(Action.kind == action_kind)
        if action_type_id is not None:
            conditions.append(Action.action_type_id == action_type_id)
        if actor_id is not None:
            conditions.append(Action.actor_id == actor_id)
        conditions.extend(self._payload_match(payload_match))
        conditions.extend(self._window(within))
        return conditions

    def _action_performed(self, node: ActionPerformedNode) -> ColumnElement[bool]:
        conditions = self._action_conditions(
            action_kind=node.action_kind,
            action_type_id=node.action_type_id,
            actor_id=node.actor_id,
            payload_match=node.payload_match,
            within=node.within,
        )
        if node.min_count == 1:
            # EXISTS stops at the first row; counting would read them all.
            return exists(select(Action.id).where(and_(*conditions)))
        counted = (
            select(func.count())
            .select_from(Action)
            .where(and_(*conditions))
            .correlate(Lead)
            .scalar_subquery()
        )
        return counted >= node.min_count

    def _action_not_performed(self, node: ActionNotPerformedNode) -> ColumnElement[bool]:
        """The "no outgoing call in 14 days" case.

        `NOT EXISTS` rather than `count = 0`: the planner can turn NOT EXISTS
        into an anti-join and stop at the first matching action per lead, where
        the count has to read every action of every lead before comparing.
        """
        conditions = self._action_conditions(
            action_kind=node.action_kind,
            action_type_id=node.action_type_id,
            actor_id=node.actor_id,
            payload_match=node.payload_match,
            within=node.within,
        )
        return not_(exists(select(Action.id).where(and_(*conditions))))

    def _transition(
        self,
        *,
        kind: SystemActionKind,
        old_key: str,
        old_value: uuid.UUID | None,
        new_key: str,
        new_value: uuid.UUID | None,
        within: Within | None,
    ) -> ColumnElement[bool]:
        """Shared shape for the two transition predicates.

        Reads `payload->>'old_*'` and `payload->>'new_*'` — the exact
        expressions `actions_status_change_idx` and `actions_assignment_idx`
        were built on in M5, which is what keeps these off a sequential scan.
        """
        conditions: list[ColumnElement[bool]] = [
            Action.lead_id == Lead.id,
            Action.workspace_id == Lead.workspace_id,
            Action.kind == kind,
        ]
        if old_value is not None:
            conditions.append(Action.payload[old_key].astext == str(old_value))
        if new_value is not None:
            conditions.append(Action.payload[new_key].astext == str(new_value))
        conditions.extend(self._window(within))
        return exists(select(Action.id).where(and_(*conditions)))

    def _status_changed(self, node: StatusChangedNode) -> ColumnElement[bool]:
        return self._transition(
            kind=SystemActionKind.STAGE_CHANGE,
            old_key="old_stage_id",
            old_value=node.from_stage_id,
            new_key="new_stage_id",
            new_value=node.to_stage_id,
            within=node.within,
        )

    def _assignee_changed(self, node: AssigneeChangedNode) -> ColumnElement[bool]:
        return self._transition(
            kind=SystemActionKind.ASSIGNMENT_CHANGE,
            old_key="old_assignee_id",
            old_value=node.from_membership_id,
            new_key="new_assignee_id",
            new_value=node.to_membership_id,
            within=node.within,
        )

    # --- free-text search --------------------------------------------------

    def search_clause(self, query: str) -> ColumnElement[bool]:
        """`?q=` — the maintained vector, plus trigrams on the identity field.

        Two mechanisms because they answer different questions. The tsvector
        matches whole words anywhere in the lead's searchable fields; the
        trigram index matches a *fragment* of the identity value, which is how
        typing the last five digits of a phone number finds it.
        """
        cleaned = query.strip()
        if not cleaned:
            return literal_column("true", type_=Boolean)

        vector = Lead.search_vector.op("@@")(func.websearch_to_tsquery(SEARCH_CONFIG, cleaned))
        fragment = Lead.identity_value.ilike(f"%{_escape_like(cleaned)}%", escape="\\")
        return or_(vector, fragment)
